# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arzymo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
