# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arzymo', '0004_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arzymo.Place')),
                ('serves_burger', models.BooleanField(default=False)),
                ('serves_butter', models.BooleanField(default=False)),
            ],
            bases=('arzymo.place',),
        ),
    ]
