# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arzymo', '0006_auto_20170724_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='blockedBy',
        ),
        migrations.AddField(
            model_name='chat',
            name='isActive1',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='isActive2',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_hash',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
